workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Pub get
        script: flutter pub get
      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app